name: Build Windows EXE
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm install
        working-directory: shared-trips-electron/electron-app

      - name: Build renderer + app
        run: npm run build
        working-directory: shared-trips-electron/electron-app

      - name: Package .exe (NSIS)
        run: npm run dist
        working-directory: shared-trips-electron/electron-app

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Shared-Trips-BG-Windows
          path: shared-trips-electron/electron-app/dist/**
