name: Build Windows EXE
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-win:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: electron-app
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps
        run: npm ci
      - name: Build renderer + app
        run: npm run build
      - name: Package .exe (NSIS)
        run: npm run dist
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Shared-Trips-BG-Windows
          path: electron-app/dist/**
